### ISSUE TITLE
Plan for updating to latest native SDK versions?

### ISSUE THREAD

**Issue by jarredt** [SiftScience/sift-react-native#2]
Hello! Was just wondering what the plan/timeline is for updating this library to use the latest native SDK versions?

It looks like Android is using v0.10.5 -- v1.0.0 was released in April.

It looks iOS is using v2.0.2 -- v2.0.3 was released a couple weeks ago.

Thanks!

**Comment by rmiestierov-sift** [comment]
Hi jarret! It's done, link for new version: 
https://github.com/SiftScience/sift-react-native/releases/tag/v0.1.3
