### ISSUE TITLE
Sift Pod version is not pinned

### ISSUE THREAD

**Issue by brodiehamilton-fanduel** [SiftScience/sift-react-native#8]
The iOS version of Sift is not pinned. Currently there is code that works with Sift version `2.1.0`

However as there was a recent update on https://github.com/SiftScience/sift-ios which published `2.1.1`, a fresh install of `sift-react-native` will install this and result in the following build error:

```
No visible @interface for 'Sift' declares the selector 'setAllowUsingMotionSensors:'
```

Screenshot:
<img width="1057" alt="Sift Version Error" src="https://user-images.githubusercontent.com/96468758/177581597-0a96e464-0071-403f-a213-467ec424ec4e.png">

My temporary solution is to add `pod 'Sift', '2.1.0'` into my Podfile but ideally control would be moved to the `sift-react-native` project

**Comment by rmiestierov-sift** [comment]
Hi @brodiehamilton-fanduel
field **setAllowUsingMotionSensors** was deleted as it is deprecated. Check out new version.
Thank you for calling out that issue
